/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.feitv.view;

import com.feitv.dao.UsuarioDAO;
import com.feitv.model.Usuario;

import javax.swing.*;
import java.awt.*;

public class TelaCadastroUsuario extends javax.swing.JFrame {

    private JTextField txtNome;
    private JTextField txtEmail;
    private JPasswordField txtSenha;
    private JPasswordField txtConfirmarSenha;
    
    public TelaCadastroUsuario() {

    setTitle("FEItv - Cadastro");
    setSize(320, 220);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    setLocationRelativeTo(null);

    JPanel painel = new JPanel();
    painel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    painel.setLayout(new GridLayout(5, 2, 5, 5));

    painel.add(new JLabel("Nome:"));
    txtNome = new JTextField();
    painel.add(txtNome);

    painel.add(new JLabel("Email:"));
    txtEmail = new JTextField();
    painel.add(txtEmail);

    painel.add(new JLabel("Senha:"));
    txtSenha = new JPasswordField();
    painel.add(txtSenha);

    painel.add(new JLabel("Confirmar Senha:"));
    txtConfirmarSenha = new JPasswordField();
    painel.add(txtConfirmarSenha);

    JButton btnCadastrar = new JButton("Cadastrar");

    painel.add(new JLabel()); // espaço vazio
    painel.add(btnCadastrar);

    btnCadastrar.addActionListener(e -> cadastrar());

    add(painel);
}

    private void cadastrar() {
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = new String(txtSenha.getPassword());
        String confirmar = new String(txtConfirmarSenha.getPassword());

        if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }

        if (!senha.equals(confirmar)) {
            JOptionPane.showMessageDialog(this, "As senhas não coincidem!");
            return;
        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email inválido!");
            return;
        }

        try {
            Usuario u = new Usuario();
            u.setNome(nome);
            u.setEmail(email);
            u.setSenha(senha);

            UsuarioDAO dao = new UsuarioDAO();
            dao.cadastrar(u);

            JOptionPane.showMessageDialog(this, "Conta criada com sucesso!");
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
